project_id = "xxttwzewtqxvpgefggah"

[functions.send-push-notification]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-toggle-pro]
verify_jwt = true

[functions.create-daily-room]
verify_jwt = true

[functions.cleanup-orphaned-users]
verify_jwt = true

[functions.create-live-stream]
verify_jwt = true

[functions.get-stream-token]
verify_jwt = true

[functions.end-live-stream]
verify_jwt = true