project_id = "xxttwzewtqxvpgefggah"
[functions.create-live-room]
enabled = true
verify_jwt = true
import_map = "./functions/create-live-room/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-live-room/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-live-room/*.html" ]

[functions.end-live-room]
enabled = true
verify_jwt = true
import_map = "./functions/end-live-room/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/end-live-room/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/end-live-room/*.html" ]
